tinyMCE.init({
	editor_selector : "page_editor",
	content_css : "/includes/styles/elements.css",
	mode : "textareas",
	document_base_url : "/",
	convert_urls : false,
	theme : "advanced",
	plugins : "paste,media,pagebreak,fullscreen,dmcbblocks",
	paste_remove_spans : true,
	paste_remove_styles : true,
	paste_strip_class_attributes : "all",
	convert_fonts_to_spans : false,
	invalid_elements : 'font',
	theme_advanced_buttons1 : "bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,blockquote,outdent,indent,|,image,media,|,link,unlink,undo,redo,|,code,fullscreen,dmcbblocks",
	theme_advanced_buttons2 : "",
	theme_advanced_buttons3 : "",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	extended_valid_elements : "iframe[class|src|width|height|scrolling|frameborder|style|allowTransparency]",
});

tinyMCE.init({
	editor_selector : "post_editor",
	content_css : "/includes/styles/elements.css",
	mode : "textareas",
	document_base_url : "/",
	convert_urls : false,
	theme : "advanced",
	plugins : "paste,media,pagebreak,fullscreen",
	paste_remove_spans : true,
	paste_remove_styles : true,
	paste_strip_class_attributes : "all",
	convert_fonts_to_spans : false,
	invalid_elements : 'font',
	theme_advanced_buttons1 : "bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,blockquote,outdent,indent,|,pagebreak,image,media,|,link,unlink,undo,redo,|,code,fullscreen",
	theme_advanced_buttons2 : "",
	theme_advanced_buttons3 : "",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	extended_valid_elements : "iframe[class|src|width|height|scrolling|frameborder|style|allowTransparency]"
});

tinyMCE.init({
	editor_selector : "template_editor",
	content_css : "/includes/styles/elements.css",
	mode : "textareas",
	document_base_url : "/",
	convert_urls : false,
	theme : "advanced",
	plugins : "paste,media,pagebreak,fullscreen,dmcbblocks",
	paste_remove_spans : true,
	paste_remove_styles : true,
	paste_strip_class_attributes : "all",
	convert_fonts_to_spans : false,
	invalid_elements : 'font',
	theme_advanced_buttons1 : "bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,blockquote,outdent,indent,|,image,media,|,link,unlink,undo,redo,|,code,fullscreen,dmcbblocks",
	theme_advanced_buttons2 : "",
	theme_advanced_buttons3 : "",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	extended_valid_elements : "iframe[class|src|width|height|scrolling|frameborder|style|allowTransparency]"
});
